// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  Options as ClientOptions,
  TDataShape,
} from '@hey-api/client-fetch'
import { client as _heyApiClient } from './client.gen'
import type {
  CreateNoteData,
  CreateNoteError,
  CreateNoteResponse,
  CreatePendingFileUploadData,
  CreatePendingFileUploadError,
  CreatePendingFileUploadResponse,
  CreatePersonData,
  CreatePersonError,
  CreatePersonResponse,
  CreateReferenceData,
  CreateReferenceError,
  CreateReferenceResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  DeleteNoteData,
  DeleteNoteError,
  DeleteNoteResponse,
  GetBlockListData,
  GetBlockListError,
  GetBlockListResponse,
  GetCommentListData,
  GetCommentListError,
  GetCommentListResponse,
  GetContentData,
  GetContentError,
  GetContentListData,
  GetContentListError,
  GetContentListResponse,
  GetContentResponse,
  GetDocumentData,
  GetDocumentError,
  GetDocumentListData,
  GetDocumentListError,
  GetDocumentListResponse,
  GetDocumentResponse,
  GetLabelListData,
  GetLabelListError,
  GetLabelListResponse,
  GetNoteData,
  GetNoteError,
  GetNoteLabelListData,
  GetNoteLabelListError,
  GetNoteLabelListResponse,
  GetNoteListData,
  GetNoteListError,
  GetNoteListResponse,
  GetNoteResponse,
  GetPersonByEmailData,
  GetPersonByEmailError,
  GetPersonByEmailResponse,
  GetPersonData,
  GetPersonError,
  GetPersonListData,
  GetPersonListError,
  GetPersonListResponse,
  GetPersonResponse,
  GetReferenceListData,
  GetReferenceListError,
  GetReferenceListResponse,
  GetSequenceDocumentListData,
  GetSequenceDocumentListError,
  GetSequenceDocumentListResponse,
  GetSequenceListData,
  GetSequenceListError,
  GetSequenceListResponse,
  GetUserData,
  GetUserError,
  GetUserListData,
  GetUserListError,
  GetUserListResponse,
  GetUserResponse,
  GetWorkspaceData,
  GetWorkspaceError,
  GetWorkspaceResponse,
  UpdatePersonData,
  UpdatePersonError,
  UpdatePersonResponse,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get block list
 * Get a list of blocks
 */
export const getBlockList = <ThrowOnError extends boolean = false>(
  options?: Options<GetBlockListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetBlockListResponse,
    GetBlockListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/block',
    ...options,
  })
}

/**
 * Get comment list
 * Get a list of comments
 */
export const getCommentList = <ThrowOnError extends boolean = false>(
  options?: Options<GetCommentListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetCommentListResponse,
    GetCommentListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/comment',
    ...options,
  })
}

/**
 * Get content list
 * Get a list of content
 */
export const getContentList = <ThrowOnError extends boolean = false>(
  options?: Options<GetContentListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetContentListResponse,
    GetContentListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content',
    ...options,
  })
}

/**
 * Get content
 * Get content by its unique identifier
 */
export const getContent = <ThrowOnError extends boolean = false>(
  options: Options<GetContentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetContentResponse,
    GetContentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/content/{contentId}',
    ...options,
  })
}

/**
 * List all documents
 * Retrieves a list of all documents accessible to the authenticated user. Optionally includes archived documents.
 */
export const getDocumentList = <ThrowOnError extends boolean = false>(
  options?: Options<GetDocumentListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetDocumentListResponse,
    GetDocumentListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/document',
    ...options,
  })
}

/**
 * Get a document
 * Get a document by its unique identifier
 */
export const getDocument = <ThrowOnError extends boolean = false>(
  options: Options<GetDocumentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDocumentResponse,
    GetDocumentError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/document/{documentId}',
    ...options,
  })
}

/**
 * Retrieve a token to upload a file
 * Retrieve a token to upload a file using the tus protocol.
 */
export const createPendingFileUpload = <ThrowOnError extends boolean = false>(
  options?: Options<CreatePendingFileUploadData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    CreatePendingFileUploadResponse,
    CreatePendingFileUploadError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/file-upload',
    ...options,
  })
}

/**
 * Get label list
 * Get a list of labels
 */
export const getLabelList = <ThrowOnError extends boolean = false>(
  options?: Options<GetLabelListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetLabelListResponse,
    GetLabelListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/label',
    ...options,
  })
}

/**
 * Get note label list
 * Get a list of note labels
 */
export const getNoteLabelList = <ThrowOnError extends boolean = false>(
  options?: Options<GetNoteLabelListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetNoteLabelListResponse,
    GetNoteLabelListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/note-label',
    ...options,
  })
}

/**
 * Get note list
 * Get a list of notes
 */
export const getNoteList = <ThrowOnError extends boolean = false>(
  options?: Options<GetNoteListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetNoteListResponse,
    GetNoteListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/note',
    ...options,
  })
}

/**
 * Create a note
 * Create a note
 */
export const createNote = <ThrowOnError extends boolean = false>(
  options?: Options<CreateNoteData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateNoteResponse,
    CreateNoteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/note',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Delete a note
 * Delete a note by its unique identifier
 */
export const deleteNote = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNoteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteNoteResponse,
    DeleteNoteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/note/{noteId}',
    ...options,
  })
}

/**
 * Get a note
 * Get a note by its unique identifier
 */
export const getNote = <ThrowOnError extends boolean = false>(
  options: Options<GetNoteData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetNoteResponse,
    GetNoteError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/note/{noteId}',
    ...options,
  })
}

/**
 * Get person list
 * Get a list of people
 */
export const getPersonList = <ThrowOnError extends boolean = false>(
  options?: Options<GetPersonListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetPersonListResponse,
    GetPersonListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/person',
    ...options,
  })
}

/**
 * Create person
 * Create a person in the workspace
 */
export const createPerson = <ThrowOnError extends boolean = false>(
  options?: Options<CreatePersonData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    CreatePersonResponse,
    CreatePersonError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/person',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Get person
 * Get a person by their ID
 */
export const getPerson = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPersonResponse,
    GetPersonError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/person/{personId}',
    ...options,
  })
}

/**
 * Update person
 * Update a person in the workspace. The person must already exist in the workspace.
 */
export const updatePerson = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePersonData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).put<
    UpdatePersonResponse,
    UpdatePersonError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/person/{personId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Get person by email
 * Get a person by their email address
 */
export const getPersonByEmail = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonByEmailData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPersonByEmailResponse,
    GetPersonByEmailError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/person/email/{email}',
    ...options,
  })
}

/**
 * Get reference list
 * Get a list of references
 */
export const getReferenceList = <ThrowOnError extends boolean = false>(
  options?: Options<GetReferenceListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetReferenceListResponse,
    GetReferenceListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/reference',
    ...options,
  })
}

/**
 * Create reference
 * Create a reference in the workspace
 */
export const createReference = <ThrowOnError extends boolean = false>(
  options?: Options<CreateReferenceData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateReferenceResponse,
    CreateReferenceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/reference',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Get sequence document list
 * Get a list of sequence documents
 */
export const getSequenceDocumentList = <ThrowOnError extends boolean = false>(
  options?: Options<GetSequenceDocumentListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetSequenceDocumentListResponse,
    GetSequenceDocumentListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/sequence-document',
    ...options,
  })
}

/**
 * Get sequence list
 * Get a list of sequences
 */
export const getSequenceList = <ThrowOnError extends boolean = false>(
  options?: Options<GetSequenceListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetSequenceListResponse,
    GetSequenceListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/sequence',
    ...options,
  })
}

/**
 * Get user list
 * Get a list of users
 */
export const getUserList = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserListData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserListResponse,
    GetUserListError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/user',
    ...options,
  })
}

/**
 * Create user
 * Create a user in the workspace
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options?: Options<CreateUserData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateUserResponse,
    CreateUserError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/user',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Get user
 * Get a user
 */
export const getUser = <ThrowOnError extends boolean = false>(
  options: Options<GetUserData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetUserResponse,
    GetUserError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/user/{userId}',
    ...options,
  })
}

/**
 * Get workspace
 * Get the workspace
 */
export const getWorkspace = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkspaceData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetWorkspaceResponse,
    GetWorkspaceError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/api/v1/workspace/current',
    ...options,
  })
}
